<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  CDATA  #REQUIRED>
  <!ATTLIST RELOCATION TYPE     CDATA  #REQUIRED>
  <!ATTLIST RELOCATION VALUE    CDATA  #REQUIRED>
  <!ATTLIST RELOCATION BYTES    CDATA  #IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  CDATA  #REQUIRED>

]>
<PROGRAM NAME="game_and_watch" EXE_PATH="/D:/genesis_mini/gamewatch/internal.bin" EXE_FORMAT="Raw Binary" IMAGE_BASE="00000000">
    <INFO_SOURCE USER="cyanic" TOOL="Ghidra 9.2" TIMESTAMP="Wed Dec 09 12:01:04 MST 2020" />
    <PROCESSOR NAME="ARM" LANGUAGE_PROVIDER="ARM:LE:32:Cortex:default" ENDIAN="little" />
    <DATATYPES>
        <ENUM NAME="HAL_StatusTypeDef" NAMESPACE="/" SIZE="0x1">
            <ENUM_ENTRY NAME="HAL_BUSY" VALUE="0x2" />
            <ENUM_ENTRY NAME="HAL_ERROR" VALUE="0x1" />
            <ENUM_ENTRY NAME="HAL_OK" VALUE="0x0" />
            <ENUM_ENTRY NAME="HAL_TIMEOUT" VALUE="0x3" />
        </ENUM>
        <STRUCTURE NAME="byte_circular_buffer" NAMESPACE="/" SIZE="0xa">
            <MEMBER OFFSET="0x0" DATATYPE="byte *" DATATYPE_NAMESPACE="/" NAME="buffer" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="mask" SIZE="0x2" />
            <MEMBER OFFSET="0x6" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="tail_index" SIZE="0x2" />
            <MEMBER OFFSET="0x8" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="head_index" SIZE="0x2" />
        </STRUCTURE>
        <STRUCTURE NAME="drawing_xy_t" NAMESPACE="/" SIZE="0x4">
            <MEMBER OFFSET="0x0" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="x" SIZE="0x2" />
            <MEMBER OFFSET="0x2" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="y" SIZE="0x2" />
        </STRUCTURE>
        <ENUM NAME="e_keys" NAMESPACE="/" SIZE="0x2">
            <ENUM_ENTRY NAME="a" VALUE="0x80" />
            <ENUM_ENTRY NAME="b" VALUE="0x40" />
            <ENUM_ENTRY NAME="charging" VALUE="0x100" />
            <ENUM_ENTRY NAME="down" VALUE="0x4" />
            <ENUM_ENTRY NAME="game" VALUE="0x400" />
            <ENUM_ENTRY NAME="left" VALUE="0x2" />
            <ENUM_ENTRY NAME="pause_set" VALUE="0x200" />
            <ENUM_ENTRY NAME="right" VALUE="0x1" />
            <ENUM_ENTRY NAME="up" VALUE="0x8" />
        </ENUM>
        <ENUM NAME="e_mode" NAMESPACE="/" SIZE="0x2">
            <ENUM_ENTRY NAME="ball" VALUE="0x8" />
            <ENUM_ENTRY NAME="clock" VALUE="0x2" />
            <ENUM_ENTRY NAME="drawing_song" VALUE="0x4" />
            <ENUM_ENTRY NAME="factory_test" VALUE="0x1" />
            <ENUM_ENTRY NAME="first_run" VALUE="0x40" />
            <ENUM_ENTRY NAME="pre_sleep" VALUE="0x80" />
            <ENUM_ENTRY NAME="smb1" VALUE="0x10" />
            <ENUM_ENTRY NAME="smb2" VALUE="0x20" />
        </ENUM>
        <ENUM NAME="e_switch_state" NAMESPACE="/" SIZE="0x1">
            <ENUM_ENTRY NAME="New_Name_(1)" VALUE="0x1" />
            <ENUM_ENTRY NAME="New_Name_(2)" VALUE="0x2" />
            <ENUM_ENTRY NAME="New_Name_(4)" VALUE="0x4" />
            <ENUM_ENTRY NAME="init" VALUE="0x5" />
            <ENUM_ENTRY NAME="none" VALUE="0x0" />
            <ENUM_ENTRY NAME="start" VALUE="0x3" />
        </ENUM>
        <STRUCTURE NAME="gif_file_header_t" NAMESPACE="/" SIZE="0xd">
            <MEMBER OFFSET="0x0" DATATYPE="char[3]" DATATYPE_NAMESPACE="/" NAME="signature" SIZE="0x3" />
            <MEMBER OFFSET="0x3" DATATYPE="char[3]" DATATYPE_NAMESPACE="/" NAME="version" SIZE="0x3" />
            <MEMBER OFFSET="0x6" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="width" SIZE="0x2" />
            <MEMBER OFFSET="0x8" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="height" SIZE="0x2" />
            <MEMBER OFFSET="0xa" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="packed_fields" SIZE="0x1" />
            <MEMBER OFFSET="0xb" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="bg_color_index" SIZE="0x1" />
            <MEMBER OFFSET="0xc" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="pixel_aspect_ratio" SIZE="0x1" />
        </STRUCTURE>
        <TYPE_DEF NAME="int8_t" NAMESPACE="/types.h" DATATYPE="char" DATATYPE_NAMESPACE="/" />
        <STRUCTURE NAME="lzw_dict_entry_t" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="offset" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="length" SIZE="0x2" />
        </STRUCTURE>
        <STRUCTURE NAME="lzw_read_buffer_t" NAMESPACE="/" SIZE="0xc">
            <MEMBER OFFSET="0x0" DATATYPE="byte *" DATATYPE_NAMESPACE="/" NAME="read_ptr" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="bits_available" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="buffer" SIZE="0x4" />
        </STRUCTURE>
        <STRUCTURE NAME="size_4_t" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="width" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="height" SIZE="0x4" />
        </STRUCTURE>
        <TYPE_DEF NAME="size_t" NAMESPACE="/stddef.h" DATATYPE="ulong" DATATYPE_NAMESPACE="/" />
        <STRUCTURE NAME="some_image_t" NAMESPACE="/" SIZE="0x14">
            <MEMBER OFFSET="0x0" DATATYPE="size_4_t *" DATATYPE_NAMESPACE="/" NAME="size" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="byte *" DATATYPE_NAMESPACE="/" NAME="a" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="byte *" DATATYPE_NAMESPACE="/" NAME="b" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="byte *" DATATYPE_NAMESPACE="/" NAME="c" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="byte *" DATATYPE_NAMESPACE="/" NAME="d" SIZE="0x4" />
        </STRUCTURE>
        <TYPE_DEF NAME="uint32_t" NAMESPACE="/stdint.h" DATATYPE="uint" DATATYPE_NAMESPACE="/" />
        <STRUCTURE NAME="unknown_3_uint_t" NAMESPACE="/" SIZE="0xc">
            <MEMBER OFFSET="0x0" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="a" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="b" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="c" SIZE="0x4" />
        </STRUCTURE>
    </DATATYPES>
    <MEMORY_MAP>
        <MEMORY_SECTION NAME="itcm_init" START_ADDR="00000000" LENGTH="0x1e5c" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="ext_flash_decrypted.bin" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="itcm_rwdata" START_ADDR="00001e5c" LENGTH="0xe58" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="itcm_rwdata.bin" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="itcm_ram" START_ADDR="00002cb4" LENGTH="0xd34c" PERMISSIONS="rwx" />
        <MEMORY_SECTION NAME="rom" START_ADDR="08000000" LENGTH="0x20000" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="int_flash.bin" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="dtcm_ram" START_ADDR="20000000" LENGTH="0x800" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="dtcm_rwdata" START_ADDR="20000800" LENGTH="0xa78" PERMISSIONS="rw">
            <MEMORY_CONTENTS FILE_NAME="dtcm_rwdata.bin" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="dtcm_ram2" START_ADDR="20001278" LENGTH="0x1ed87" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="axi_sram1" START_ADDR="24000000" LENGTH="0x40000" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="axi_sram2" START_ADDR="24040000" LENGTH="0x60000" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="axi_sram3" START_ADDR="240a0000" LENGTH="0x60000" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="ahb_sram1" START_ADDR="30000000" LENGTH="0x10000" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="ahb_sram2" START_ADDR="30010000" LENGTH="0x10000" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="srd_sram" START_ADDR="38000000" LENGTH="0x8000" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="backup_sram" START_ADDR="38800000" LENGTH="0x1000" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="otfdec1" START_ADDR="5200b800" LENGTH="0x400" PERMISSIONS="rw" VOLATILE="y" />
        <MEMORY_SECTION NAME="ext_flash" START_ADDR="90000000" LENGTH="0xf5870" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="ext_flash_decrypted.bin" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
    </MEMORY_MAP>
    <REGISTER_VALUES>
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000003a" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000003b" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000040" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000041" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000009e" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000009f" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000130" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000131" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000013e" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000013f" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000018e" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000018f" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001b0" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001b1" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001b4" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001b5" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001c8" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001c9" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001ca" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001cb" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001ee" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001ef" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001f2" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000001f3" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000208" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000209" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000020c" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000020d" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000210" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000211" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000220" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000221" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000023e" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000023f" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000242" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000243" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000002d8" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000002d9" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000002dc" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="000002dd" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000306" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000307" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000030a" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000030b" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000334" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000335" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000338" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000339" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000a48" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000a49" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000a4a" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000a4b" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000ae6" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000ae7" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000aea" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00000aeb" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000194c" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000194d" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001996" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001997" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000199a" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="0000199b" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001a8c" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001a8d" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001a8e" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001a8f" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b40" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b41" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b42" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b43" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b4a" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b4b" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b5e" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b5f" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b94" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b95" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b98" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b99" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b9c" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001b9d" LENGTH="0x3" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001ba0" LENGTH="0x1" />
        <REGISTER_VALUE_RANGE REGISTER="TMode" VALUE="0x1" START_ADDRESS="00001ba1" LENGTH="0x3" />